# language: python
# python:
#   - "2.7"

before_script:
  - id -un
  - python -V                                   # Print out python version for debugging
  # Uncomment next line if your Django app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  # - sudo apt-get update
  - pip install -r requirements.txt --user

# before_install: "sudo apt-get update"
# install: "pip install -q -r requirements.txt"
Test:
  script: 
    - python test_ncbot.py
  # branches:
  #   only:
  #     - master